# Generated by Django 6.0.2 on 2026-02-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='daily_url',
            field=models.URLField(blank=True, help_text='Daily.co Room URL', null=True),
        ),
    ]
