# Generated by Django 6.0.2 on 2026-02-07 08:12

import core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path, validators=[core.validators.validate_file_type]),
        ),
    ]
