# Generated by Django 6.0.2 on 2026-02-07 07:48

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(max_length=50, blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(max_length=50, blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
