# Generated by Django 6.0.2 on 2026-02-07 07:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True, null=True),
        ),
    ]
