# Generated by Django 6.0.2 on 2026-02-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('OFFICE_ADMIN', 'Office Admin'), ('HR_EXEC', 'HR Executive'), ('HR_MANAGER', 'HR Manager'), ('RECRUITER', 'Recruiter'), ('PAYROLL_OFFICER', 'Payroll Officer'), ('MANAGER', 'Manager'), ('TEAM_LEAD', 'Team Lead'), ('PROJECT_MANAGER', 'Project Manager'), ('DEPT_HEAD', 'Department Head'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('BACKEND_DEV', 'Backend Developer'), ('FRONTEND_DEV', 'Frontend Developer'), ('DEVOPS', 'DevOps Engineer'), ('QA_ENGINEER', 'QA Engineer'), ('ACCOUNTANT', 'Accountant'), ('FINANCE_MANAGER', 'Finance Manager'), ('OPERATIONS_EXEC', 'Operations Executive'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('SALES_EXEC', 'Sales Executive'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING_EXEC', 'Marketing Executive'), ('MARKETING_MANAGER', 'Marketing Manager'), ('SUPPORT_EXEC', 'Support Executive'), ('SUPPORT_MANAGER', 'Support Manager')], default='SOFTWARE_ENGINEER', max_length=20),
        ),
    ]
