# Generated by Django 6.0.2 on 2026-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_auth_type',
            field=models.CharField(choices=[('NONE', 'None'), ('APP', 'Authenticator App'), ('EMAIL', 'Email OTP'), ('SMS', 'SMS OTP')], default='NONE', max_length=10),
        ),
    ]
