# Generated by Django 6.0.2 on 2026-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_two_factor_auth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth_type',
            field=models.CharField(choices=[('NONE', 'None'), ('APP', 'Authenticator App'), ('EMAIL', 'Email OTP'), ('SMS', 'SMS OTP')], default='EMAIL', max_length=10),
        ),
    ]
