# Generated by Django 6.0.2 on 2026-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Frontend route to redirect to', max_length=255, null=True),
        ),
    ]
